# Generated by Django 5.1.7 on 2025-03-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0003_alter_customuser_email_alter_customuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
