# Generated by Django 5.1.7 on 2025-03-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0004_alter_producto_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='cantidad',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
